name: Packer

on:
  workflow_dispatch:

jobs:
  packer:
    environment: demo
    env:
      managed_image_name: devops-mi-nginx-${{github.run_number}}
      resource_group_name: devops-iaas
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: linux-nginx-azure.json
          working_directory: src/packer

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var tenant_id=$${{ secrets.tenant_id }} -var client_id=${{ secrets.client_id }} -var client_secret=${{ secrets.client_secret }} -var subscription_id=${{ secrets.subscription_id }} -var resource_group_name=${{ env.resource_group_name }} -var managed_image_name=${{ env.managed_image_name }} "
          target: linux-nginx-azure.json
          working_directory: src/packer
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts